name: Check types
on:
  pull_request_target:
    branches:
      - main
    paths:
      - "**.tsx?"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
env:
  NODE_OPTIONS: "--max-old-space-size=8192"
jobs:
  check-types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2

      - name: Use Node 16.x
        uses: actions/setup-node@v3
        
        with:
          node-version: 16.x
          cache: "yarn"
      
      - name: Show info
        run: node -e "console.log(require('v8').getHeapStatistics())"
      
      - run: yarn --frozen-lockfile
      - run: yarn type-check
