name: Cleanup Preview Databases

env:
  SNAPLET_ACCESS_TOKEN: ${{ secrets.SNAPLET_ACCESS_TOKEN }}
  SNAPLET_PROJECT_ID: cl4u26bwz7962859ply7ibuo43t

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: snaplet/action@v1
        if: ${{ env.SNAPLET_ACCESS_TOKEN && env.SNAPLET_PROJECT_ID }}
        with:
          delete: true
